# Generated by Django 5.0.7 on 2026-01-14 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientprofile_gender'),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_description', models.TextField(verbose_name='Описание приёма пищи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary_photos/', verbose_name='Фото блюда')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории (примерно)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белки')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жиры')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Углеводы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'Запись в дневнике питания',
                'verbose_name_plural': 'Записи в дневнике питания',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
