# Generated by Django 5.0.7 on 2026-01-14 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_nutritiondiaryentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddiaryentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Запись в дневнике питания', 'verbose_name_plural': 'Записи в дневнике питания'},
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='food_description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='NutritionDiaryEntry',
        ),
    ]
