# Generated by Django 5.0.7 on 2026-01-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_alter_fooddiaryentry_options_fooddiaryentry_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddiaryentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snacks', 'Перекусы'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
