# Generated by Django 5.0.7 on 2026-01-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_fooddiaryentry_meal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Запись прогресса', 'verbose_name_plural': 'Записи прогресса'},
        ),
    ]
