# Generated by Django 5.0.7 on 2026-01-17 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_alter_progressrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
