# Generated by Django 6.0.1 on 2026-01-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_progressrecord_created_at'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='product',
        ),
        migrations.CreateModel(
            name='DiaryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='В граммах или штуках', max_digits=6)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='diaries.fooddiaryentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт в записи',
                'verbose_name_plural': 'Продукты в записи',
            },
        ),
    ]
