# Generated by Django 5.0.7 on 2026-01-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='dietary_preferences',
            field=models.TextField(blank=True, verbose_name='Предпочтения в питании'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='height',
            field=models.SmallIntegerField(blank=True, help_text='в см', null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='initial_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Начальный вес'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, verbose_name='Медицинские условия'),
        ),
    ]
