# Generated by Django 5.0.7 on 2026-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '— Выберите —'), ('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, verbose_name='Пол'),
        ),
    ]
