# Generated by Django 5.0.7 on 2026-01-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('type', models.CharField(choices=[('in_person', 'Очно'), ('online', 'Онлайн')], max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Проведена'), ('cancelled', 'Отменена'), ('missed', 'Пропущена')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritionists.nutritionistprofile')),
            ],
        ),
    ]
