# Generated by Django 5.0.7 on 2026-01-17 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='type',
        ),
        migrations.AddField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(default='2026-01-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='consultation',
            name='purpose',
            field=models.TextField(blank=True, help_text='Цель консультации'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, help_text='Заметки после консультации'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Проведена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20),
        ),
    ]
