# Generated by Django 5.0.7 on 2026-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionprogram',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
