# Generated by Django 5.0.7 on 2026-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_nutritionprogram_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymealplan',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='breakfast',
            field=models.TextField(blank=True, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='dinner',
            field=models.TextField(blank=True, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='lunch',
            field=models.TextField(blank=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='snacks',
            field=models.TextField(blank=True, verbose_name='Перекусы'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymealplan',
            unique_together={('program', 'date')},
        ),
    ]
