# Generated by Django 5.0.7 on 2026-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_dailymealplan_options_dailymealplan_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealplan',
            name='breakfast_done',
            field=models.BooleanField(default=False, verbose_name='Завтрак выполнен'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='breakfast_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время завтрака'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='dinner_done',
            field=models.BooleanField(default=False, verbose_name='Ужин выполнен'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='dinner_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время ужина'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='lunch_done',
            field=models.BooleanField(default=False, verbose_name='Обед выполнен'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='lunch_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время обеда'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='snacks_done',
            field=models.BooleanField(default=False, verbose_name='Перекусы выполнены'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='snacks_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время перекуса'),
        ),
    ]
