# Generated by Django 5.0.7 on 2026-01-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_nutritiondiaryentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionDiaryEntry',
        ),
    ]
