# Generated by Django 5.0.7 on 2026-01-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('client_invitation', 'Приглашение от нутрициолога'), ('consultation_scheduled', 'Консультация назначена')], max_length=50),
        ),
    ]
