# Generated by Django 5.0.7 on 2026-01-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100g', models.SmallIntegerField()),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
